variables:
  GIT_SUBMODULE_STRATEGY: normal

.build:
  stage: build
  tags:
    - docker
  image: "docker.io/screemer/psc-toolchain5:latest"
  script:
    - "# Build kernel"
    - make defconfig KBUILD_DEFCONFIG="${KBUILD_DEFCONFIG}"
    - make oldconfig
    - make prepare
    - make
    - make INSTALL_MOD_STRIP=1  modules_install
    - make firmware_install
    - "# Build package"
    - rm -rf build_output
    - mkdir build_output
    - cd uboot-support
    - /bin/bash ./packit.sh
    - cp -r boot.img ../build_output/
    - cd ..
    - "# Add compiled kernel  modules"
    - mkdir -p build_output/modules
    - mkdir -p build_output/firmware
    - find . -name '*.ko' -exec cp --parents \{\} /lib/modules \;
    - rm -rf build_output/modules/build_output
    - cp -R /lib/firmware/* build_output/firmware
    - cd build_output
    - md5sum boot.img > boot.md5
  artifacts:
    paths:
      - build_output/

arm_debug:
  extends: .build
  variables:
    ARCH: arm
    KBUILD_DEFCONFIG: autobleem_defconfig
    CROSS_COMPILE: arm-unknown-linux-gnueabihf-

